import { cacheLife, cacheTag } from "next/cache";
import { records } from "@/lib/records";
import { getSupabase, hasSupabase } from "@/lib/supabase";
import type { LabData, PlannedWeekRow, RaceRow, ThresholdKind, ThresholdRow } from "./types";

const num = (v: unknown): number | undefined => (v === null || v === undefined ? undefined : Number(v));
const str = (v: unknown): string | undefined => (v === null || v === undefined || v === "" ? undefined : String(v));

/** Power curve: the database copy when it exists, otherwise the file generated by `npm run strava:records`. */
function fromFile(): Record<string, number> {
  return Object.fromEntries(Object.entries(records.power ?? {}).map(([d, p]) => [d, p.watts]));
}

/**
 * Everything the /lab page reads from Supabase (thresholds, races, planned weeks, power curve).
 * An empty or missing table is not an error: the page falls back to estimates.
 */
export async function getLabData(): Promise<LabData> {
  "use cache";
  cacheLife({ stale: 120, revalidate: 900, expire: 86400 });
  cacheTag("strava-live");

  const empty: LabData = { dbReady: false, thresholds: [], races: [], plannedWeeks: [], power: fromFile() };
  if (!hasSupabase()) return empty;

  try {
    const db = getSupabase();
    const [th, rc, wk, pc] = await Promise.all([
      db.from("thresholds").select("kind,test_date,value,unit,notes").order("test_date", { ascending: false }),
      db.from("races").select("*").order("race_date", { ascending: false }),
      db.from("training_weeks").select("week_start,title,planned_hours").order("week_start", { ascending: true }),
      db.from("power_curve").select("duration_s,watts"),
    ]);
    for (const r of [th, rc, wk, pc]) if (r.error) throw new Error(r.error.message);

    const thresholds: ThresholdRow[] = (th.data ?? []).map((r) => ({
      kind: r.kind as ThresholdKind,
      testDate: String(r.test_date).slice(0, 10),
      value: Number(r.value),
      unit: String(r.unit),
      notes: str(r.notes),
    }));
    const races: RaceRow[] = (rc.data ?? []).map((r) => ({
      id: Number(r.id),
      name: String(r.name),
      date: String(r.race_date).slice(0, 10),
      location: str(r.location),
      distanceLabel: str(r.distance_label),
      finishSeconds: num(r.finish_seconds),
      swimSeconds: num(r.swim_seconds),
      t1Seconds: num(r.t1_seconds),
      bikeSeconds: num(r.bike_seconds),
      t2Seconds: num(r.t2_seconds),
      runSeconds: num(r.run_seconds),
      overallRank: num(r.overall_rank),
      categoryRank: num(r.category_rank),
      category: str(r.category),
      notes: str(r.notes),
    }));
    const plannedWeeks: PlannedWeekRow[] = (wk.data ?? []).map((r) => ({
      weekStart: String(r.week_start).slice(0, 10),
      title: str(r.title),
      plannedHours: num(r.planned_hours),
    }));

    const power = fromFile();
    for (const r of pc.data ?? []) power[String(r.duration_s)] = Number(r.watts);

    return { dbReady: true, thresholds, races, plannedWeeks, power };
  } catch (e) {
    console.error("Lab: could not read the database:", e);
    return empty;
  }
}
