import raw from "@/data/records.json";

/** Power-curve durations shown on the site, in seconds: 5 s, 10 s, 30 s, 1 min, 5 min, 10 min, 20 min, 1 h, 2 h, 3 h. */
export const POWER_DURATIONS = [5, 10, 30, 60, 300, 600, 1200, 3600, 7200, 10800] as const;

export interface PowerBest {
  watts: number;
  id: number;
  name: string;
  date: string;
  indoor: boolean;
}

export interface RecordsData {
  generatedAt: string | null;
  /** how many activities were analyzed out of the total that qualify */
  analyzed: { rides: number };
  total: { rides: number };
  /** key = duration in seconds */
  power: Record<string, PowerBest>;
}

/**
 * Power curve. Generated by `npm run strava:records` (see README) because
 * Strava only exposes the power stream one activity at a time, which would blow the API rate limit if done
 * on every page refresh. Includes indoor rides (trainer, Zwift).
 */
export const records = raw as unknown as RecordsData;

export function powerLabel(seconds: number): string {
  if (seconds < 60) return `${seconds}s`;
  if (seconds < 3600) return `${seconds / 60}m`;
  return `${seconds / 3600}h`;
}
